
#pragma once

//////////////////////////////////////////////////////////////////////////
//all msg
#define MSG_APP_EXAM_SCORE_CHANGE           (WM_APP + 1)
#define MSG_APP_VIRUS_SCAN_FOUND_VIRUS      (WM_APP + 2)
#define MSG_APP_DEFAULT_NAVIGATE            (WM_APP + 3)
#define MSG_APP_VIRUS_SCAN_CLEAN_VIRUS      (WM_APP + 4)
#define MSG_APP_ECHO_FINISH                 (WM_APP + 5)
#define MSG_APP_PROTECTION_SWITCH_CHANGE    (WM_APP + 6)
#define MSG_APP_EXAM_ONLY_ECHO              (WM_APP + 7)
#define MSG_APP_UPDATE_CHECK_FINISH         (WM_APP + 8)
#define MSG_APP_UPDATE_PROGRESS             (WM_APP + 9)
#define MSG_APP_SHOW_MSGBOX					(WM_APP + 10)
#define MSG_APP_EXAM_PROGRESS               (WM_APP + 11)
#define MSG_APP_DELAY_EXAM                  (WM_APP + 12)
#define MSG_APP_DELAY_NAVIGATE_IE           (WM_APP + 13)
#define MSG_APP_IEFIX_FINISHED				(WM_APP + 14)
#define MSG_APP_EXAM_ERROR					(WM_APP + 15)
#define MSG_APP_AV_ENGINE_INSTALL_FINISH    (WM_APP + 16)
#define MSG_APP_GOTO_MAIN_TAB				(WM_APP + 17)

#define MSG_APP_ZHUANSHA_INFO_REFRESH       (WM_APP + 18)
#define MSG_APP_FULL_SCAN_TROJAN			(WM_APP + 19)	
#define MSG_SCAN_END						(WM_APP + 20)

#define	MSG_APP_POWERSWEEP_PROG_STEP		(WM_APP + 21)

#define MSG_APP_BWS_USER_DATA_CHANGED	    (WM_APP + 23)
#define MSG_APP_PROTECTION_CTRL_LOAD_FINISH (WM_APP + 24)
#define MSG_APP_PROTECTION_LOG_LOAD_FINISH  (WM_APP + 25)

#define MSG_APP_BWS_USER_DATA_PROCESS_LOAD_FINISH  (WM_APP + 26)
#define MSG_APP_BWS_USER_DATA_URL_____LOAD_FINISH  (WM_APP + 27)
#define MSG_APP_BWS_USER_DATA_HISTORY_LOAD_FINISH  (WM_APP + 28)

#define MSG_APP_IEFIX_SWITCH_PAGE (WM_APP + 29)

#define MSG_APP_LOAD_UPDATE_CACHE			(WM_APP + 30)
#define MSG_APP_LOAD_UPDATE_REAL			(WM_APP + 31)
#define MSG_APP_LOAD_BWS_FINISHED			(WM_APP + 32)
#define MSG_APP_SHOW_IECLEAN_DATA			(WM_APP + 33)
#define MSG_APP_START_EXAM					(WM_APP + 34)
#define MSG_APP_TRAY_CALL_FIXLEAK			(WM_APP + 35)
#define	MSG_APP_TROJAR_TRUST				(WM_APP + 36)
#define	MSG_APP_IEFIX_TRUST					(WM_APP + 37)
#define MSG_APP_UPDATE_WHITEINFO			(WM_APP + 38)
#define MSG_CLEAN_FINISH					(WM_APP + 39)
#define MSG_SCRIPT_CLEAN_FINISH				(WM_APP + 40)
#define MSG_APP_KEX_CLEAN_FINISH			(WM_APP + 41)
#define MSG_APP_SETWHITE					(WM_APP + 42)
#define MSG_APP_SHOW_PLUG_CLEAN				(WM_APP + 43)
#define MSG_APP_VIRUS_VIEW_INFO				(WM_APP + 44)
#define MSG_APP_PLUG_MENU_POP				(WM_APP + 45)
#define WM_MSG_CALL_DUBA					(WM_APP + 46)

//plug
#define MSG_PLUG_SCAN_BEGIN				(WM_APP+1000)
#define MSG_PLUG_SCAN_PROGRESS			(MSG_PLUG_SCAN_BEGIN+1)
#define MSG_PLUG_SCAN_FIND				(MSG_PLUG_SCAN_BEGIN+2)
#define MSG_PLUG_SCAN_FINISH			(MSG_PLUG_SCAN_BEGIN+3)
#define MSG_PLUG_REMOVE_ITEM_BEGIN		(MSG_PLUG_SCAN_BEGIN+4)
#define MSG_PLUG_REMOVE_ITEM_END		(MSG_PLUG_SCAN_BEGIN+5)
#define MSG_PLUG_REMOVE_FINISH			(MSG_PLUG_SCAN_BEGIN+6)
#define MSG_PLUG_SCAN_ITEM_CHANGE		(MSG_PLUG_SCAN_BEGIN+7)
#define MSG_PLUG_SCAN_LOAD_LIB_FAIL		(MSG_PLUG_SCAN_BEGIN+8)

#define MSG_PLUG_SCAN_ENG				MSG_PLUG_SCAN_BEGIN+999

//listview
#define MSG_USER_LDLISTVIEWCTRL_BEGIN WM_APP+2000
#define MSG_USER_LDLISTVIEWCTRL_LBP_URL MSG_USER_LDLISTVIEWCTRL_BEGIN+1//如果用户点击了URL，就会像用户发送这个消息，WPARAM 行号，LPARAM URL的索引
#define MSG_USER_LDLISTVIEWCTRL_LBP_EXTXT MSG_USER_LDLISTVIEWCTRL_BEGIN+2//如果用户点击了EXTXT, 就会像用户发送这个消息，WPARAM 行号，LPARAM EXTXT的索引
#define MSG_USER_LDLISTVIEWCTRL_LBP_BTN   MSG_USER_LDLISTVIEWCTRL_BEGIN+3
#define MSG_USER_LDLISTVIEWCTRL_EXPAND	  MSG_USER_LDLISTVIEWCTRL_BEGIN+4//展开操作
#define MSG_USER_LDLISTVIEWCTRL_NOTIFY	  MSG_USER_LDLISTVIEWCTRL_BEGIN+5//LISTVIEW中需要回调给主窗口的消息
#define MSG_USER_LDLISTVIEWCTRL_END MSG_USER_LDLISTVIEWCTRL_BEGIN+999

//////////////////////////////////////////////////////////////////////////
// system optimizie

#define MSG_SYSOPT_BEGIN			(WM_APP+3000)

#define MSG_SYSOPT_RUN_SCAN_FIND	(MSG_SYSOPT_BEGIN+1)
#define MSG_SYSOPT_RUN_SCAN_END		(MSG_SYSOPT_BEGIN+2)
#define MSG_SYSOPT_RUN_RESTORE_END	(MSG_SYSOPT_BEGIN+3)	
#define MSG_SYSOPT_RUN_FIRST_IN		(MSG_SYSOPT_BEGIN+4)
#define	MSG_SYSOPT_ONEKEYOPT_END	(MSG_SYSOPT_BEGIN+5)
#define MSG_SYSOPT_CHANGE_IGNORED_NUM	(MSG_SYSOPT_BEGIN+6)
#define MSG_SYSOPT_REFRESH_ONEKEYOPT	(MSG_SYSOPT_BEGIN+7)
#define MSG_SYSOPT_RESTORE_DELAYRUN		(MSG_SYSOPT_BEGIN+8)

//////////////////////////////////////////////////////////////////////////
//all timer id
#define XX_PLUG_PROGRESS_SCAN_TIMER_ID		1001
#define XX_PLUG_PROGRESS_REMOVE_TIMER_ID	1002
#define EXAM_TIMER_SHOWLISTVIEW				1003
#define EXAM_TIMER_PROGRESS					1004
#define IEFIX_SCAN_TIMER_PROGRESS_ID        1005
#define IEFIX_SCAN_TIMER_ANTI_ID			1006
#define IEFIX_UPDATE_PROGRESS_TEXT			1007
#define TIMER_ID_PROC						1008
#define TIMER_ID_REFRESH_KWS_STATUS			1009
#define TIMER_ID_EXAM_KWS_PROGRESS			1010
#define TIMER_ID_RUNOPT_AUTOOPT_TOPTIP		1011
#define TIMER_ID_LOADING_INFO				1012
#define TIMER_ID_UPDTAE_VIRUS_TAB			1013
#define TIMER_ID_CHECKINSTALL_DUBA			1014
#define TIMER_ID_EXAMSCORE_ID				1015
#define	TIMER_SOFT_UNINSTALL				1016
#define	TIMER_ID_MAIN_DLG_ONCE				1017
#define	TIMER_ID_VIRUSCAN_ONCE				1018
#define TIMER_ID_DELAYLOAD_KSAFE_TOOL		1019

#define MSG_KSWEB_IEFIX				(WM_APP+4000)
#define MSG_KSWEB_IEFIX_PROGRESS			(MSG_KSWEB_IEFIX+1)
#define MSG_KSWEB_IEFIX_SCAN_END			(MSG_KSWEB_IEFIX+2)
#define MSG_KSWEB_IEFIX_RESULT_CHECK		(MSG_KSWEB_IEFIX+3)
#define MSG_KSWEB_IEFIX_REMOVE_END			(MSG_KSWEB_IEFIX+4)
#define MSG_KSWEB_IEFIX_INIT_DATA			(MSG_KSWEB_IEFIX+5)

//////////////////////////////////////////////////////////////////////////
// 软件管理
#define WM_NET_ERROR_REFRESH			(WM_USER + 800)
#define WM_BOTTOM_REFRESH				(WM_USER + 801)
#define WM_LOADTIP_REFRESH				(WM_USER + 802)
#define WM_UPDATE_SOFT_COUNT			(WM_USER + 805)
#define WM_SOFT_REFRESH_ITEM			(WM_USER + 806)
#define WM_SOFT_REFRESH_CANLIU			(WM_USER + 807)	// 残留项的显示
#define WM_SOFT_UNI_ALL_REFRESH_FINISH	(WM_USER + 808)	
#define WM_SOFT_UE_DATA_COMPLETED		(WM_USER + 803)
#define WM_SOFT_FRESH_TOTAL				(WM_USER + 804)
#define WM_SOFT_UE_HIDE_HEADER_ARROW	(WM_USER + 812)
#define WM_SOFT_UE_SORT_BY_NAME			(WM_USER + 813)
#define WM_SOFT_UE_SHOW_UNIDATAPAGE		(WM_USER + 814)
#define WM_SOFT_INSTALL_CHECK			(WM_USER + 809)	// 检测软件是否可以安装
#define WM_SOFT_INSTALL_NOTIFY			(WM_USER + 810)	// 通知刚刚有一个软件安装
#define WM_SOFT_ONEKEY_DLG_EXIT			(WM_USER + 811)	// 快速装机对话框退出
/* 手动升级 */
#define WM_UPDATE_PROGRESS              (WM_USER + 901)
#define WM_UPDATE_CHECK_VERSION         (WM_USER + 902)
#define WM_UPDATE_DOWNLOAD_FINISH       (WM_USER + 903)